feat: add result page to devcon round branch
privacy-scaling-explorations/maci-platform pull request #494
Opened 2024-11-20 19:14 UTC by kittybest

**Description**
Simple display of the tally result at the result page.

**Notice**
Still need to be e2e tested.

2024-11-21 11:24 UTC, ctrlc03 requested changes
Thanks, just two changes to make, tested it and it works

2024-11-21 11:24 UTC, ctrlc03 commented on packages/interface/src/config.ts
> +export const getPimlicoRPCURL = (): string | undefined => {
this should be deleted as it's a duplicate

2024-11-21 11:24 UTC, ctrlc03 commented on pnpm-lock.yaml
>          specifier: ^19.4.1
need to regenerate the lock file

2024-11-21 14:40 UTC, ctrlc03 approved these changes
Thanks

2024-11-21 15:39 UTC, 0xmad reviewed
@kittybest thanks, just left some comments

2024-11-21 17:58 UTC, kittybest commented on package.json
> +    "@typescript-eslint/eslint-plugin": "^7.0.0",
This is just the result of rebase, maybe that's because the version `^7.0.0` is used after the `^7.17.0`? Let me upgrade it back

2024-11-21 19:33 UTC, 0xmad commented on packages/interface/src/pages/rounds/[pollId]/result/index.tsx
> +    }
I think it makes sense to use EMedal starting from 0. So you can use only one line:
```suggestion
    return rank <= EMedal.Bronze ? rank : undefined.
```

2024-11-22 18:22 UTC, 0xmad reviewed
@kittybest thanks, just two improvements and I'm good with this PR.
Just fix the types ci job (not sure if e2e can be fixed here).

2024-11-22 18:22 UTC, 0xmad commented on packages/interface/src/pages/rounds/[pollId]/result/index.tsx
> +    rank <= (EMedal.Bronze as number) ? (rank as EMedal) : undefined;
Let's use `useCallback` here

2024-11-22 18:22 UTC, 0xmad commented on packages/interface/src/utils/types.ts
>  }
```suggestion
export enum EMedal {
  Gold,
  Silver,
  Bronze,
}
```

2024-11-22 19:49 UTC, kittybest commented
> @kittybest thanks, just two improvements and I'm good with this PR. Just fix the types ci job (not sure if e2e can be fixed here).

For the `types` check, I discussed before with @ctrlc03, that this is a problem that might not be able to be solved now, the error message looks like this:
![image](https://github.com/user-attachments/assets/8068ea81-fd08-4bae-850d-6be8f498d912)

The KernelSmartAccount can not fit in the client type, but the code does work. Seems like they might not be using `permissionless` package afterward.

2024-11-25 14:07 UTC, merged